People/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using DAL.FNhibernate.Entities;
using DAL.FNhibernate.Repositories;

namespace People.Controllers
{
    public class SearchController : Controller
    {
        private readonly IUrlRepository urlRepository;
        readonly string domainName = ConfigurationManager.AppSettings["DomanName"];
        int UrlsPerPage = int.Parse(ConfigurationManager.AppSettings["SearchResultsPerPage"]);

        public SearchController(IUrlRepository urlRepository)
        {
            this.urlRepository = urlRepository;
        }

        public ActionResult Index(string query, int pageNumber = 0)
        {
//            if (string.IsNullOrEmpty(query) || query.Length < 2)
//            {
//                return View("Search");
//            }
            int count;
            IList<UrlMapping> urlMappings = urlRepository.GetUrls(query, pageNumber, out count);

            ViewBag.DomainNameWithDot = "." + domainName;
            ViewBag.query = query;
            ViewBag.IsPreviousLinkVisible = pageNumber > 0;
            ViewBag.IsNextLinkVisible = UrlsPerPage * (pageNumber+1) < count;
            ViewBag.PageNumber = pageNumber;
            ViewBag.TotalCount = Math.Ceiling((decimal)count/(UrlsPerPage*(pageNumber+1)));
            
            return View(urlMappings);    
        }

    }
}

People/Views/Search/Index.cshtml
@model IList<DAL.FNhibernate.Entities.UrlMapping>

@{
    ViewBag.Title = "Search ..";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 class="text-center">Search results..</h2>
<div class="container">
    <div class="hero-unit">
        @if(Model.Count == 0){
            <small class="text-center text-warning"> No results found. </small>
        }
        else
        {
            int pageNumberFromOne = @ViewBag.PageNumber + 1;
                <span class="pull-right text-warning small-texty">Page: @pageNumberFromOne of @ViewBag.TotalCount</span>
            <br/>
            foreach (var url in Model)
            {
                //todo: pagination bitch !

                string fullUrl = "http://" + url.Url + @ViewBag.DomainNameWithDot;
                string fullUrlWithoutProtocol = url.Url + @ViewBag.DomainNameWithDot;
                <div class="text-center">
                    <a href="@fullUrl" target="_blank" >@fullUrlWithoutProtocol</a>
                </div>
            }
            bool isPreviousLinkVisible = ViewBag.IsPreviousLinkVisible ?? false;
            bool isNextLinkVisible = ViewBag.IsNextLinkVisible ?? false;
            if (isPreviousLinkVisible)
                {
                    <a id="previousLink" href="@Url.Action("Index","Search",new{@ViewBag.query, pageNumber = @ViewBag.PageNumber - 1})" class="pull-left text-warning"> &lt; PreviousPage</a>
                }
                if (isNextLinkVisible)
                {
                    <a id="nextLink" href="@Url.Action("Index","Search",new{@ViewBag.query, pageNumber = @ViewBag.PageNumber + 1})" class="pull-right text-warning"> NextPage &gt; </a>
                }
        }
    </div>
</div>

People/Views/Search/Search.cshtml
@model dynamic

@{
    ViewBag.Title = "Search ..";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="container">
    <div class="hero-unit">
        <h4 class="text-center text-error">Please enter 2 or more characters to search..</h4>
    </div>
</div>